[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "boseqx"
version = "0.1.0"
description = "A Python-native mathematical framework for quantum mathematics."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Dev Kumar" }
]

dependencies = [
    "numpy",
    "sympy"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.pytest.ini_options]
testpaths = ["tests"]